// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numRuns= Integer.parseInt(args[0]);
		int greaterThan = 0;
		int lessThan = 0;
		int i = 0;

		while(i < numRuns) {
			double random = Math.random();
			if (random > 0.5) {
				greaterThan++;
			}
			 else {
				lessThan++;
			}
			i++;
		}

		double ratio = (double) Math.min(greaterThan, lessThan) / Math.max(greaterThan, lessThan);

		System.out.println("> " + "0.5: " + greaterThan + " times");
		System.out.println("<= " + "0.5: " + lessThan + " times");

		if (ratio != 0) {
			System.out.println("Ratio: " + ratio);
		}


	}
}
